"""add chat session document links

Revision ID: bbdb56a16c17
Revises: 90b27d450069
Create Date: 2026-07-20 01:51:49.261595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbdb56a16c17'
down_revision: Union[str, Sequence[str], None] = '90b27d450069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'document_id', name='uq_chat_session_document')
    )
    op.create_index(op.f('ix_chat_session_documents_document_id'), 'chat_session_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_chat_session_documents_session_id'), 'chat_session_documents', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_session_documents_session_id'), table_name='chat_session_documents')
    op.drop_index(op.f('ix_chat_session_documents_document_id'), table_name='chat_session_documents')
    op.drop_table('chat_session_documents')
    # ### end Alembic commands ###
